[[shards]]
name = "Boston"
shardID = 0
address = "localhost:8080"

[[shards]]
name = "New York"
shardID = 1
address = "localhost:8081"

[[shards]]
name = "Chicago"
shardID = 2
address = "localhost:8082"

[[shards]]
name = "San Francisco"
shardID = 3
address = "localhost:8083"

[[shards]]
name = "Denver"
shardID = 4
address = "localhost:8084"
